call rules_oss_audit_setup() in getting started docs.
When I use the rules in a separate repo I get the following error:
```
ERROR: /home/luxe/Desktop/repos/bazel-buildfarm/BUILD:144:10: every rule of type oss_audit implicitly depends upon the target '@rules_oss_audit//oss_audit/tools:generate_boms', but this target could not be found because of: error loading package '@rules_oss_audit//oss_audit/tools': Unable to find package for @oss_audit_deps//:requirements.bzl: The repository '@oss_audit_deps' could not be resolved: Repository '@oss_audit_deps' is not defined.
Documentation for implicit attribute _generate_boms of rules of type oss_audit:
Generates the BOM and BOM-issues files and validates oss package usage
```

Maybe I'm missing something because I thought transitive workspaces were evaluated and therefore the requirements.bzl should have already been generated.  My workaround is to call `rules_oss_audit_setup()` in my own workspace.